# Generated by Django 5.0.7 on 2025-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_emailverificationcode_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='External avatar URL (used when avatar is not available)'),
        ),
    ]
