# Generated by Django 5.0.7 on 2025-11-28 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wardrobes',
            },
        ),
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('outerwear', 'Outerwear'), ('dress', 'Dress'), ('bag', 'Bag')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('primary_image', models.ImageField(blank=True, null=True, upload_to='wardrobe/items/')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], default='all', max_length=20)),
                ('tags', models.JSONField(default=list, help_text='List of tags for categorization')),
                ('notes', models.TextField(blank=True)),
                ('purchase_link', models.URLField(blank=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('times_worn', models.IntegerField(default=0)),
                ('last_worn_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wardrobe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wardrobe.wardrobe')),
            ],
            options={
                'db_table': 'wardrobe_items',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeItemAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'wardrobe_item_attributes',
            },
        ),
        migrations.CreateModel(
            name='WardrobeItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='wardrobe/items/')),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'wardrobe_item_images',
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeItemWearLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worn_date', models.DateField()),
                ('outfit_id', models.IntegerField(blank=True, help_text='Optional reference to outfit', null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wear_logs', to='wardrobe.wardrobeitem')),
            ],
            options={
                'db_table': 'wardrobe_item_wear_logs',
                'ordering': ['-worn_date'],
            },
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['wardrobe', 'category'], name='wardrobe_it_wardrob_fa3817_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['wardrobe', '-created_at'], name='wardrobe_it_wardrob_5f46e8_idx'),
        ),
        migrations.AddIndex(
            model_name='wardrobeitem',
            index=models.Index(fields=['is_deleted'], name='wardrobe_it_is_dele_ce702e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='wardrobeitemattribute',
            unique_together={('item', 'key')},
        ),
        migrations.AddIndex(
            model_name='wardrobeitemwearlog',
            index=models.Index(fields=['item', '-worn_date'], name='wardrobe_it_item_id_a24751_idx'),
        ),
    ]
