# Generated by Django 5.2.7 on 2025-11-14 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='outfits/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='outfits/thumbnails/')),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('work', 'Work/Professional'), ('formal', 'Formal'), ('party', 'Party/Event'), ('sport', 'Sport/Active'), ('date', 'Date'), ('travel', 'Travel')], max_length=20)),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], max_length=20)),
                ('style_tags', models.JSONField(default=list, help_text='List of style tags (e.g., minimalist, boho, streetwear)')),
                ('color_palette', models.JSONField(default=list, help_text='Primary colors in the outfit')),
                ('ai_generated', models.BooleanField(default=False)),
                ('confidence_score', models.FloatField(blank=True, help_text='AI confidence score (0-1)', null=True)),
                ('embedding_vector', models.JSONField(blank=True, help_text='Image embedding for similarity search', null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('saves_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('dress', 'Dress'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessory', 'Accessory'), ('bag', 'Bag'), ('jewelry', 'Jewelry')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='outfit_items/')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('size', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('material', models.CharField(blank=True, max_length=100)),
                ('purchase_url', models.URLField(blank=True)),
                ('affiliate_link', models.URLField(blank=True)),
                ('retailer', models.CharField(blank=True, max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('product_id', models.CharField(blank=True, help_text='External product ID', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='outfits.outfit')),
            ],
            options={
                'db_table': 'outfit_items',
                'ordering': ['item_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='OutfitLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='outfits.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfit_likes',
            },
        ),
        migrations.CreateModel(
            name='OutfitSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(blank=True, help_text='Optional collection name', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='outfits.outfit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfit_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'outfit_saves',
            },
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['user', '-created_at'], name='outfits_user_id_058aaa_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['occasion', 'season'], name='outfits_occasio_4ea3c9_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['-likes_count'], name='outfits_likes_c_5a4fe9_idx'),
        ),
        migrations.AddIndex(
            model_name='outfit',
            index=models.Index(fields=['is_public', '-created_at'], name='outfits_is_publ_e91ee7_idx'),
        ),
        migrations.AddIndex(
            model_name='outfitlike',
            index=models.Index(fields=['user', '-created_at'], name='outfit_like_user_id_403ceb_idx'),
        ),
        migrations.AddIndex(
            model_name='outfitlike',
            index=models.Index(fields=['outfit', '-created_at'], name='outfit_like_outfit__4cec15_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outfitlike',
            unique_together={('user', 'outfit')},
        ),
        migrations.AddIndex(
            model_name='outfitsave',
            index=models.Index(fields=['user', '-created_at'], name='outfit_save_user_id_a689d0_idx'),
        ),
        migrations.AddIndex(
            model_name='outfitsave',
            index=models.Index(fields=['outfit', '-created_at'], name='outfit_save_outfit__363c44_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='outfitsave',
            unique_together={('user', 'outfit')},
        ),
    ]
