# Generated by Django 5.0.7 on 2025-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfits', '0002_outfit_main_image_url_outfititem_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='outfititem',
            index=models.Index(fields=['outfit', 'item_type'], name='outfit_item_outfit__c8753f_idx'),
        ),
    ]
