# Generated by Django 5.0.7 on 2025-11-28 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('outfits', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lookbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, upload_to='lookbooks/')),
                ('season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('all', 'All Season')], max_length=20)),
                ('occasion', models.CharField(choices=[('casual', 'Casual'), ('work', 'Work'), ('formal', 'Formal'), ('party', 'Party'), ('travel', 'Travel'), ('vacation', 'Vacation')], max_length=20)),
                ('style', models.JSONField(default=list, help_text='Style tags')),
                ('tags', models.JSONField(default=list, help_text='General tags')),
                ('likes_count', models.IntegerField(default=0)),
                ('views_count', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('is_public', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lookbooks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LookbookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='lookbooks.lookbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lookbook_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lookbook_likes',
            },
        ),
        migrations.CreateModel(
            name='LookbookOutfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lookbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='lookbooks.lookbook')),
                ('outfit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_lookbooks', to='outfits.outfit')),
            ],
            options={
                'db_table': 'lookbook_outfits',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lookbook',
            index=models.Index(fields=['creator', '-created_at'], name='lookbooks_creator_a29a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbook',
            index=models.Index(fields=['is_public', 'is_featured', '-likes_count'], name='lookbooks_is_publ_7194b0_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbook',
            index=models.Index(fields=['season', 'occasion'], name='lookbooks_season_ce707f_idx'),
        ),
        migrations.AddIndex(
            model_name='lookbooklike',
            index=models.Index(fields=['lookbook', '-created_at'], name='lookbook_li_lookboo_7bbc2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lookbooklike',
            unique_together={('user', 'lookbook')},
        ),
        migrations.AlterUniqueTogether(
            name='lookbookoutfit',
            unique_together={('lookbook', 'outfit')},
        ),
    ]
