# Generated by Django 5.0.7 on 2025-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lookbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookbook',
            name='cover_image_url',
            field=models.URLField(blank=True, help_text='External cover image URL (used when cover_image is not available)'),
        ),
    ]
