# Generated by Django 5.0.7 on 2025-11-28 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (used when image is not available)'),
        ),
    ]
