# Generated by Django 5.0.7 on 2025-11-28 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_postimage_image_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='postimage',
            index=models.Index(fields=['post', 'order'], name='post_images_post_id_8637ba_idx'),
        ),
    ]
